# Generated by Django 4.2.6 on 2024-02-14 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionorder',
            name='supplies',
        ),
        migrations.AddField(
            model_name='productionorder',
            name='supplies',
            field=models.ManyToManyField(to='production.supplies', verbose_name='Insumos'),
        ),
    ]
