# Generated by Django 4.2.6 on 2024-02-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplies',
            name='supplieCode',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='Código'),
        ),
    ]
