# Generated by Django 4.2.6 on 2023-12-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productionorder',
            name='Production_OrderDate',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha pedido produccion'),
        ),
    ]
