# Generated by Django 4.2.6 on 2024-03-13 18:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('postulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payAmount', models.FloatField(verbose_name='Valor Pago')),
                ('payTipe', models.CharField(choices=[('Total', 'Total'), ('Parcial', 'Parcial')], max_length=50, verbose_name='Tipo de Pago')),
                ('payMethod', models.CharField(choices=[('Efectivo', 'Efectivo'), ('TarjetaDeCredito', 'Tarjeta de crédito'), ('TarjetaDebito', 'Tarjeta débito')], default='Efectivo', max_length=50, verbose_name='Metodo de Pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockProduct', models.IntegerField(verbose_name='Cantidad Producto')),
                ('purchaseOrderDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha pedido')),
                ('state', models.CharField(choices=[('Recibido', 'Recibido'), ('EnProduccion', 'En producción'), ('EnCamino', 'En camino'), ('Finalizado', 'Finalizado')], max_length=50, verbose_name='Estado Pedido')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Orden pedido',
                'verbose_name_plural': 'ordenpedidos',
                'db_table': 'ordenpedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saleDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha Venta')),
                ('saleAmount', models.FloatField(verbose_name='Valor Venta')),
                ('saleSubAmount', models.FloatField(verbose_name='Valor Subtotal')),
                ('saleIvaAmount', models.IntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (19, '19%')], verbose_name='Valor IVA')),
                ('employed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.employed', verbose_name='Empleado')),
                ('pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.pays', verbose_name='Pago')),
                ('purchaseOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.purchaseorder', verbose_name='Orden de pedido')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='pays',
            name='purchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.purchaseorder'),
        ),
    ]
