# Generated by Django 4.2.6 on 2023-11-09 07:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'cliente',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaleDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha Venta')),
            ],
        ),
        migrations.CreateModel(
            name='Pays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payAmount', models.FloatField(verbose_name='Valor Pago')),
                ('payMetod', models.CharField(max_length=50, verbose_name='Medio Pago')),
                ('payTipe', models.CharField(max_length=50, verbose_name='Tipo pago')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'db_table': 'pagos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StockProduct', models.IntegerField(verbose_name='Cantidad Producto')),
                ('PurchaseOrderDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha pedido')),
                ('State', models.CharField(max_length=50, verbose_name='Estado Pedido')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
            ],
            options={
                'verbose_name': 'Orden pedido',
                'verbose_name_plural': 'ordenpedidos',
                'db_table': 'ordenpedido',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SaleDate', models.DateTimeField(default=datetime.datetime.now, verbose_name='Fecha Venta')),
                ('SaleAmount', models.FloatField(verbose_name='Valor Venta')),
                ('SaleSubAmount', models.FloatField(verbose_name='Valor Subtotal')),
                ('SaleDisAmount', models.FloatField(verbose_name='Valor Descuento')),
                ('SaleIvaAmount', models.FloatField(verbose_name='Valor IVA')),
                ('Client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.client')),
                ('Employed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.employed')),
                ('Pays', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.pays')),
                ('PurchaseOrder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.purchaseorder')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'db_table': 'ventas',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='pays',
            name='PurchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.purchaseorder'),
        ),
    ]
