# Generated by Django 4.2.6 on 2024-02-05 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0001_initial'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pays',
            name='payMetod',
        ),
        migrations.RemoveField(
            model_name='sales',
            name='SaleDisAmount',
        ),
        migrations.AlterField(
            model_name='pays',
            name='payTipe',
            field=models.CharField(choices=[('Total', 'Total'), ('Parcial', 'Parcial')], max_length=50, verbose_name='Tipo de Pago'),
        ),
        migrations.AlterField(
            model_name='purchaseorder',
            name='State',
            field=models.CharField(choices=[('Recibido', 'Recibido'), ('EnProduccion', 'En producción'), ('EnCamino', 'En camino'), ('Finalizado', 'Finalizado')], max_length=50, verbose_name='Estado Pedido'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Employed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.employed', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='Pays',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.pays', verbose_name='Pago'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='PurchaseOrder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sales.purchaseorder', verbose_name='Orden de pedido'),
        ),
        migrations.AlterField(
            model_name='sales',
            name='SaleIvaAmount',
            field=models.IntegerField(choices=[(0, '0%'), (5, '5%'), (10, '10%'), (19, '19%')], verbose_name='Valor IVA'),
        ),
    ]
