# Generated by Django 4.2.6 on 2024-02-06 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_remove_pays_paymetod_remove_sales_saledisamount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pays',
            name='payMethod',
            field=models.CharField(default='Efectivo', max_length=50, verbose_name='Metodo de Pago'),
        ),
    ]
