# Generated by Django 4.2.6 on 2024-02-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_pays_paymethod'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pays',
            name='payMethod',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('TarjetaDeCredito', 'Tarjeta de crédito'), ('TarjetaDebito', 'Tarjeta débito')], default='Efectivo', max_length=50, verbose_name='Metodo de Pago'),
        ),
    ]
