# Generated by Django 4.2.6 on 2023-12-12 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='Categoria')),
                ('descriptCategory', models.CharField(max_length=50, verbose_name='Descripcion categoria')),
            ],
            options={
                'verbose_name': 'Sugerencias',
                'verbose_name_plural': 'Sugerencias',
                'db_table': 'buzonsugerencias',
                'ordering': ['id'],
            },
        ),
    ]
