# Generated by Django 4.2.6 on 2024-02-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suggestions', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestions',
            options={'ordering': ['id'], 'verbose_name': 'Sugerencia', 'verbose_name_plural': 'Sugerencias'},
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='category',
            field=models.CharField(choices=[('mobiliario', 'Mobiliario'), ('violencia_laboral', 'Violencia Laboral'), ('acoso_laboral', 'Acoso Laboral'), ('festividades', 'Festividades')], max_length=50, verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='suggestions',
            name='descriptCategory',
            field=models.CharField(max_length=50, verbose_name='Descripción de la Categoría'),
        ),
    ]
