# Generated by Django 4.2.6 on 2024-03-18 21:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shipping_addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShippingAddresses',
            new_name='ShippingAddress',
        ),
    ]
