# Generated by Django 4.2.7 on 2023-11-10 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre')),
                ('last_name', models.CharField(max_length=255, verbose_name='Apellido')),
                ('document_number', models.CharField(max_length=20, verbose_name='Número de documento')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('phone_number', models.IntegerField(verbose_name='Número de teléfono')),
                ('gender', models.CharField(max_length=10, verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=55, verbose_name='Puesto')),
                ('job_offers', models.IntegerField(verbose_name='Cantidad de Puestos')),
                ('descrip_offers', models.CharField(max_length=250, verbose_name='Descripción del cargo')),
                ('start_offers', models.DateTimeField(verbose_name='Fecha de publicación de la oferta')),
                ('close_offers', models.DateTimeField(verbose_name='Fecha de Cierre de la oferta')),
                ('experience', models.IntegerField(verbose_name='Experiencia Requerida')),
                ('studies', models.CharField(max_length=250, verbose_name='Estudios')),
                ('type_contract', models.CharField(max_length=25, verbose_name='Tipo de Contrato')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'postulacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='Fecha del Agendamiento')),
                ('time', models.TimeField(verbose_name='Hora del Agendamiento')),
                ('interviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='postulation.employed')),
                ('postulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.postulation')),
            ],
            options={
                'verbose_name': 'Agendamiento',
                'verbose_name_plural': 'Agentamientos',
                'db_table': 'agendamiento',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(max_length=20, verbose_name='Tipo de Contrato')),
                ('start_date', models.DateField(verbose_name='Fecha de Inicio')),
                ('end_date', models.DateField(verbose_name='Terminación de Contrato')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Salario')),
                ('position', models.CharField(max_length=255, verbose_name='Puesto')),
                ('Employed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.employed')),
                ('postulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.postulation')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
                'ordering': ['id'],
            },
        ),
    ]
