# Generated by Django 4.2.6 on 2023-11-03 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=55, verbose_name='Puesto')),
                ('job_offers', models.IntegerField(max_length=15, verbose_name='Cantidad de Puestos')),
                ('descrip_offers', models.CharField(max_length=250, verbose_name='Descripción del cargo')),
                ('start_offers', models.DateTimeField(verbose_name='Fecha de publicación de la oferta')),
                ('close_offers', models.DateTimeField(verbose_name='Fecha de Cierre de la oferta')),
                ('experience', models.IntegerField(max_length=15, verbose_name='Experiencia Requerida')),
                ('studies', models.CharField(max_length=250, verbose_name='Estudios')),
                ('type_contract', models.CharField(max_length=25, verbose_name='Tipo de Contrato')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'postulacion',
                'ordering': ['id'],
            },
        ),
    ]
