# Generated by Django 4.2.7 on 2023-11-15 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Details_Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.IntegerField(verbose_name='Salario')),
                ('funtions', models.CharField(max_length=250, verbose_name='Funciones')),
            ],
            options={
                'verbose_name': 'Detalle de Oferta',
                'verbose_name_plural': 'Detalles de Ofertas',
                'db_table': 'descripoferta',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Employed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
            options={
                'verbose_name': 'Empleado',
                'verbose_name_plural': 'Empleados',
                'db_table': 'empleado',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_position', models.CharField(max_length=250, verbose_name='Descripción del cargo')),
            ],
            options={
                'verbose_name': 'Cargo',
                'verbose_name_plural': 'Cargos',
                'db_table': 'cargo',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Postulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_offers', models.DateTimeField(verbose_name='Fecha de la oferta')),
                ('descrip_offer', models.CharField(max_length=250, verbose_name='Descripción de la Oferta')),
                ('profile_postulation', models.CharField(max_length=250, verbose_name='Perfil postulación')),
                ('Details_Offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.details_offer')),
                ('Employed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.employed')),
            ],
            options={
                'verbose_name': 'Postulación',
                'verbose_name_plural': 'Postulaciones',
                'db_table': 'postulacion',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='State_Postulations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descrip_State', models.CharField(max_length=250, verbose_name='Descripción Postulación')),
            ],
            options={
                'verbose_name': 'Estado Postulación',
                'verbose_name_plural': 'Estado Postulaciones',
                'db_table': 'estadopostulaciones',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='TypeContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrip_contract', models.CharField(max_length=250, verbose_name='Descripción del Contrato')),
            ],
            options={
                'verbose_name': 'Tipo de Contrato',
                'verbose_name_plural': 'Tipos de Contratos',
                'db_table': 'tipocontrato',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Scheduling',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_interview', models.DateTimeField(verbose_name='Fecha de la entrevista agendamiento')),
                ('postulation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.postulation')),
            ],
            options={
                'verbose_name': 'Agendamiento',
                'verbose_name_plural': 'Agentamientos',
                'db_table': 'agendamiento',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='postulation',
            name='State_Postulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.state_postulations'),
        ),
        migrations.AddField(
            model_name='employed',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.position'),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_date', models.DateField(verbose_name='Fecha del Contrato')),
                ('Employed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.employed')),
                ('TypeContract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.typecontract')),
            ],
            options={
                'verbose_name': 'Contrato',
                'verbose_name_plural': 'Contratos',
                'db_table': 'contrato',
                'ordering': ['id'],
            },
        ),
    ]
