# Generated by Django 4.2.6 on 2023-11-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postulation',
            name='Details_Offer',
        ),
        migrations.AlterField(
            model_name='contract',
            name='Employed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.employed', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='TypeContract',
            field=models.CharField(max_length=50, verbose_name='Tipo de Contrato'),
        ),
        migrations.AlterField(
            model_name='employed',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.position', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='Employed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.employed', verbose_name='Empleado'),
        ),
        migrations.AlterField(
            model_name='postulation',
            name='State_Postulations',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='postulation.state_postulations', verbose_name='Estado Postulaciones'),
        ),
        migrations.DeleteModel(
            name='Details_Offer',
        ),
        migrations.DeleteModel(
            name='TypeContract',
        ),
    ]
