# Generated by Django 4.2.6 on 2024-02-07 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employed',
            name='position',
            field=models.CharField(choices=[('Administrador', 'Administrador'), ('JefeDeVentas', 'Jefe de ventas'), ('JefeDeProduccion', 'Jefe de produccion'), ('Secretaria', 'Secretaria')], max_length=55, verbose_name='Cargo'),
        ),
    ]
