# Generated by Django 4.2.6 on 2024-02-09 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='TypeContract',
            field=models.CharField(choices=[('TerminoFijo', 'Término Fijo'), ('Indefinido', 'Indefinido'), ('ObraoLabor', 'Obra o labor'), ('Temporal', 'Temporal')], max_length=50, verbose_name='Tipo de Contrato'),
        ),
    ]
