# Generated by Django 4.2.6 on 2023-11-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0002_remove_postulation_details_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employed',
            name='position',
            field=models.CharField(max_length=55, verbose_name='Cargo'),
        ),
        migrations.DeleteModel(
            name='position',
        ),
    ]
