# Generated by Django 4.2.6 on 2023-11-17 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postulation', '0003_alter_employed_position_delete_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulation',
            name='State_Postulations',
            field=models.TextField(verbose_name='Estado Postulaciones'),
        ),
        migrations.DeleteModel(
            name='State_Postulations',
        ),
    ]
