# Generated by Django 4.2.6 on 2024-03-13 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre')),
                ('stock', models.IntegerField(verbose_name='Cantidad')),
                ('fabricationDate', models.DateField(auto_now_add=True, verbose_name='Fecha de fabricación')),
                ('size', models.CharField(help_text='1L - 25x25CM', max_length=12, verbose_name='Tamaño')),
                ('color', models.CharField(max_length=20, verbose_name='Color')),
                ('slug', models.SlugField(unique=True)),
                ('productCode', models.IntegerField(blank=True, editable=False, null=True, verbose_name='Código')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('state', models.CharField(choices=[('Selecciona', 'Selecciona'), ('producción', 'En producción'), ('alistamiento', 'En alistamiento'), ('stock', 'En stock'), ('Agotado', 'Agotado')], default='Selecciona', help_text='Seleccione el estado', max_length=40, verbose_name='Estado')),
                ('category', models.CharField(choices=[('selecciona', 'Selecciona'), ('Portacomidas', 'Portacomidas'), ('Ganchos', 'Ganchos'), ('Envases', 'Envases'), ('Atomizadores', 'Atomizadores')], default='selecciona', help_text='Seleccione la categoría', max_length=20, verbose_name='Categoría')),
                ('image', models.ImageField(blank=True, null=True, upload_to='media', verbose_name='Imagen producto')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'producto',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateFlow', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de flujo')),
                ('FlowType', models.CharField(choices=[('Entrada', 'Entrada'), ('Salida', 'Salida')], max_length=50, verbose_name='Tipo de flujo')),
                ('Product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product')),
                ('supplies', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.supplies')),
            ],
            options={
                'verbose_name': 'Flujo',
                'verbose_name_plural': 'Flujos',
                'db_table': 'flujo',
                'ordering': ['id'],
            },
        ),
    ]
