# Generated by Django 4.2.6 on 2024-02-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('selecciona', 'Selecciona'), ('Portacomidas', 'Portacomidas'), ('Ganchos', 'Ganchos'), ('Envases', 'Envases'), ('Atomizadores', 'Atomizadores')], default='selecciona', help_text='Seleccione la categoría', max_length=20, verbose_name='Categoría'),
        ),
    ]
