# Generated by Django 4.2.6 on 2024-02-08 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productCode',
            field=models.IntegerField(blank=True, editable=False, null=True, verbose_name='Código'),
        ),
    ]
