# Generated by Django 4.2.6 on 2023-12-12 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='fabricationDate',
            field=models.DateField(verbose_name='Fecha de fabricacion'),
        ),
    ]
