# Generated by Django 4.2.6 on 2024-02-05 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
        ('inventory', '0003_alter_flow_product_alter_flow_supplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='Product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Producto'),
        ),
        migrations.AlterField(
            model_name='flow',
            name='supplies',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='production.supplies', verbose_name='Insumo'),
        ),
    ]
