# Generated by Django 4.2.6 on 2024-02-05 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_alter_flow_product_alter_flow_supplies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flow',
            name='DateFlow',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de flujo'),
        ),
    ]
